### ISSUE TITLE
demo version

### ISSUE THREAD

**Issue by 0ul0** [aidewoode/jekyll-theme-mint#3]
demo version don't work.

**Comment by aidewoode** [comment]
What demo?

**Comment by StewBen** [comment]
I think @zxcgloomed probably means the one which is linked at the top-right of the GitHub page. That is [aidewoode.github.io/jekyll-theme-mint/](https://aidewoode.github.io/jekyll-theme-mint/), which links to [https://aidewoode.com/jekyll-theme-mint/](https://aidewoode.com/jekyll-theme-mint/). It's a bit empty compared to the preview in the readme, and the "About" link is bugged. Here's a screenshot from running it on Google Chrome:
![bild](https://user-images.githubusercontent.com/13822835/178038747-c386eb61-cb35-4700-8a16-4420650efdb9.png)

**Comment by aidewoode** [comment]
Hi @StoicAurora , Could you give me more details about the OS and browser you are using? Cause I don't have the same style issue on my laptop. I think it's a css style issue on specific OS or browser.

**Comment by StewBen** [comment]
Of course, Chrome Version 103.0.5060.114 (Official version) (64 bits) running on Windows 10 Enterprise Version 20H2.
